
server:
  port: 9090

spring:
  datasource:
    name: test
    url: jdbc:mysql://115.159.193.114:3306/db_formdata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: zhao2020
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  servlet:
    multipart:
      max-request-size: 10MB   
      max-file-size: 10MB
  devtools:
    restart:
      enabled: true
      exclude: templates
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    mode: HTML
    suffix: .html
  resources:
    static-locations: classpath:/static
  redis:
    port: 6379
    host: 127.0.0.1
    database: 3
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zx.formdata.entity
logging:
  level:
    com.zx.formdata.mapper: debug